[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09ac72b31c77c06618045f359ca21f07d5f8ec65"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "73d49794c868844a2cefd21376dfc7d8b98e2ea375714c697d63ad20534aaf32"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cadb0da6bb0bfdaa33e7c565c5deb4092b44c30"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "c050ded2d46a284488742e33bd5f8daa6ef91c6bcf411b353e60eab90560401a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03a7dc6fc648c03c9e3a6b205ba7876bbf247819"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ba3dc94d26b937aeed93dc264c157941ffdb84c6da484b6b8fa5f9bae2fde322"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "300568b556698cee804a72875404965ad9b21852"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ebeae834108e82617fc6ca498cd789fe9fbaad702ee88006b037d00dfe367bd0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e8f679987a5dfa5efe06e30a64d2fbe3ede59a1"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "fc60ee7bf6f8d51a6fb265a2b6cefccb017a6f68471400b443b734e091ab7441"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3666437e8f01ba8d22ea190a95a431dcb9ec5d0f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "917644588b041a476e48de6e35603df13ec9c49b4f2ff63639c30788d74ef1be"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff0eec9116cd2bc94d6d29bcbfc35e5b1bf9fbef"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "eb2ac91847e7287dbbd6c8b89f01c370cead6cb3f5445e02f6a1093420f829e6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8d6c612855938c9bbd6a32efa4728eb9bcdd988"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "20693af7bb2476fbf980dedec5a378b01eb108589cc3ced0a1313c5b8daa50e0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07e1b47e977df5e0147f38e86e5c296e5d518e8d"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "68d5a59eec6e5cf281c008074179e5cafbb05b9cf1c5cec4444f22498002c21a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27ae06d95e8d8eb966f3d176844410de47be2394"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e48993c631483894448e57c60d52935e7c3f46d03998441996ddc9cfdb0ec528"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a3727efbf12aa783e657a0397c12473bf8af4c0"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "dc06301f9aaa0e2163c44ff86951676c7412525f64bfbbf0452b9d65974e333f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0451efc8f435419e3d453cfeda352a16a82f7536"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5f679e208be47f440dc3e6713c73336087933b6414d5b45acbd3466bd7985f1f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "621794ddf62108bb98ce1ac45da827a5b5af9903"
os = "windows"

    [[Enzyme.download]]
    sha256 = "632797406d51d99db7d59913f9fae1209b18c5e45f19d4634d7c5cbe6114e27e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf0306d8c44f7a9f071d3bfef7f599d3fad637f6"
os = "windows"

    [[Enzyme.download]]
    sha256 = "84c0a763bb8aa0e0568f73686c4b90d982843b66f7f2abad071709de5d20c6b3"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2dcd0f5f42a849ff6baa1fcf43de579237426e1e"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "87280fe066b1cfe50b5c5c1615cf506be85e35df6ff8a05bc47068ea80603143"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1237efb80639ffec38e709089711a81e753356e2"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1345fb6428bf6ec4ca0d4121006e5851b263caf19f1df8d75e74376b42e2c056"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "684b8ce8cbe7ac3ddb07ce065cf2045d4211b3fb"
os = "macos"

    [[Enzyme.download]]
    sha256 = "f0c0ca6c2ad3d3de3666901a9891df5f01709ee2c4d0d9a9204b3038b6de7284"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af5e29b20f8829e4ddf3f5efd63e54c39bc228f8"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "718420fbf6077c344a33580fde383767fecabac6ba3a2e331f3bf853beea29de"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2657658477fc19883e4ad106aa22c045265f507f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1c267188ea021882acd0e69438a92e882e3794af9740ead707477d304ce8f81b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46018c811dd3f57a44b6c51277058fa47319c266"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "bb689829b6fbf2fcb3911d5819fbfbcca9121b22ad41cc57d585c45b80712ed4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b841fa2a6ec19933a5716c9d5bab8a69631a6c7"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "f21f3994f5e96f1a3c369d6544d9756268c6ed6a2253651129816a353c13f3f6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "7cefccb325b8b7078fa8efd742b72c54b298073e"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "08e7f7d290106698febbd472c685da54deee88040da6c267fee13116dc3b07fb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43aca8f5a0ee2732d538417abddd6daf9bdb8335"
os = "windows"

    [[Enzyme.download]]
    sha256 = "2891f5f53d5837d44ab674a479b95a7fd0128f245a9ad07b0046275f61a73fa3"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d962881ce48a69be3031081b171ecf36ccfb2df9"
os = "windows"

    [[Enzyme.download]]
    sha256 = "79ab675a5496cd22993dad40bb224fb5dca4f9798b8df9450a603b62d9d34c61"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.5+0/Enzyme.v0.0.5.x86_64-w64-mingw32-cxx11.tar.gz"
