[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39c683f2e6a9206a1317577ca5b668faaaafa3b4"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d6cb5f47a989e1614e024724cc57ebefc8f905526763a740bae73ae2f09fc5e7"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a039d41f7e7167c2db71ee5a60678be7c29ad89"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1a158b867c3ace2ea5156ff6bddee5ddd0bcf6239b04b0846a39c5aa5be97f38"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3904758767d9eda69122f9e47f73ea8c57615d97"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "4b37b41779632377796ceb93d6026415953df42a87820d770aebad8b9c782c14"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aa3f04c224e59b1f0b2c0447cc498a9d8c8b4a3"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "0c5af4fd8bdc1e114c8b9a7fdc59afd14af24664a5436a8b8b47479541f9164b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b9731e69bbb6b761a2e137081a27a97137f338a"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "67e6931d061efb2c7beab12303c3e4fb0f93f2e42360f6c252c8191049b48676"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f22ba0c699500fe2fb7be01d6e1609bb8362b87"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "777022ff4875febe5a39a6778bc3010d4b68a1a82fbb4f2b8af3dc02ae5e24c8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd929183a348e445fc9f9be40fba8367eec93ce5"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "877628b46d00d4d65e0cfb21dc06b3bf19fe7e6721e85395bfa55c94b09be9dd"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1fbd9d2b5311f4bf31c6d089291508796a650f2"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1cc445ef56dabf1ca9ec48bec93ffe52a4eb932da7b80c63d097d8be30b012da"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcd2aa9e5a1cb385d83892942aae3127ee79ea51"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "dace2a16545f819147e3600d255f4a258fd7368d36c23a59fb2f0b94ff06f89b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50637eea737dca4fc8562cd1a8c6a096b23f923e"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "717c622d0fcf4d1ae5a10f6e9bc2ad6148a2ef111f9c27f3c61747adc78d77fa"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a5656a3d4fb44edcef009e3bdf6830148edca92"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "8af9924933710040f71c0d1c62864cb9a1f1e07bd566d77d7cb09e950ad2b21f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1534f33351fe64dc3b97c3d215f021f9d345978a"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "dec4dc8cda6e419600da515d1947e2ddb1913e07084a83069827eda460763947"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f89c45ecfc7c81b44cf01e3ce8e0170a545c124b"
os = "windows"

    [[Enzyme.download]]
    sha256 = "3fd981e969bb123a0cc11303ef2e4aef27577d1176747093302838906e77d77c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c6191b94a0dfae6cc58421d93c94ff1da28b780"
os = "windows"

    [[Enzyme.download]]
    sha256 = "c3c213f2450fc8b434a250cb8e1713b4a8015e5421be1b973f40558a84f5033f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b1ef8741c22ee15b3875986049b5d37114a6bb0"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "679b5fd78b0098b192434d45975901f6fab7b04238e7c2c8a31693d08f58ede2"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95928a2fab2a505e0a76466997de89e3430eeb43"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "89b15ecf24a57a3aa0f548f24b3585cbccf1660efb2959ec1f6e727f3c477217"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "8fd08a377b32cacc6a55e818d65ea6439f32cbef"
os = "macos"

    [[Enzyme.download]]
    sha256 = "73afedcf0cae47df004d71a024e93ccb97ecc93b1427578748c432383dbc6fac"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18eea0210c046832ba99a89bea60ea9baf069b7d"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "da6faec62d042597c664bb525981070be8d5baf8e07b3858e6ef9e768360adca"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0542f4764c349c081da1c970a212cb40a34a84dd"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "6e09159d7f95721236ce7e0a67b60c99156b734a60d9c7ce0ad46f5aea2615a8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a10b9f9c5b445d4598b11bb4edddc143234face"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "6463cbb3ea753f2b9140da144bbc91a1cbc2426a401ad9629de4a4e9cef26c77"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9c1810809c20f9618c81f8f6b0a0d524cb14104"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d19f20f75e8f0e1d27d28074d4b3c900634464f9a14fbde586fa6666d284d64a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "36b0ddef5789ccb1ea84a0103b5c1327737bb44f"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "facc55df3597f77b75c433b056d5ce560e5f3367cb3aff9c3b17a860ceb68463"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d119b61cb0c9ad8e3e575bc5bc65880636b1230d"
os = "windows"

    [[Enzyme.download]]
    sha256 = "98368dcbd80f3c5844b7a4e23633300dc7f5670862bc6189293b25ec0e55362a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be4327c13d657137464be69fab4ec72ef6d9ee02"
os = "windows"

    [[Enzyme.download]]
    sha256 = "a0618ff91579db0750f59b886f791adb91c5d04af6e488cec4bdd6fd42b8dc28"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.8+0/Enzyme.v0.0.8.x86_64-w64-mingw32-cxx11.tar.gz"
