[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3340d7403067af6f8ebe3ea4c3689583aacc15b8"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "9f035c7cfbb69dd7b551b40ddcd5bb74d8702c167c2ff20685f1011ad6e72494"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "076d0a42d6ca6f3c31f262d67827a52e5aa695f5"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "9c2f1d1520d4de0fa4f8454f114a2554c3640d4304419c57e1b1636031592ce1"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d2f68aa47a595adbe26df4b441dc48daa97ea7a"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "780b7ab04ffbae036841856a9bb3d9d6e40be671460d976a7731d9e7256d0fc3"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06b384ae631105f2ce6f8374f47997b5bbc074f1"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "8db9d3cb502d70f82a006d09d638e7f02c5caa70fa4f7b2fa4018f1b8fc93c18"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d2b120af3b3ed7955183a8a1ddb70af569ef311"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d77302ea1d8b0b2db1e289b08e561131c9e1eda4aee15b6e426f09b1d0fad3c4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14b8f15d01b9d787bf65ed6ee539f77f354e313b"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "a7d928742ffcb313262244319ff6ca5aa9695c1210b3dafcdf7ae596b0a0147a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4df762bd5daa04c41d3d56e7a45dd84a37edbeae"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "98bf9c4d39be339aa5f1da9513b63fedcd28862eab854eb8ac6996a1c45f070f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "444256861eec95fb2f69c5be022d288950450894"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "b50bd3a72a78b58a234b57db84cfa3e6ddd16dcf1a711f962a4282faf17d0b38"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0ea190527e503f8fc69cbddcf003e70483e383e"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "19d9b6472d712025f1eebcfdcc2ed40f65a459a43252b4f02fe7e728dcd8d75f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3417b3db15936d822886c2a7ec928a065fda2d94"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "214b38b89eaaab4f35241097f53b380435d061bc6c516e6d2b648c213333db8f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "957359b761df039dca7dedf73240c2ce028b4aef"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5c55a6af2dbfdb2fad0137fbfd1feca8f6e66149da1a296004f1483e7e468d9d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4e3a627f5e7122bf0f2f5d415766a35c5675044"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ab0e8389e2e593fc30f5a19770638c424a1526a6b1ac7a804e29a4784c50b625"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d476d7fc9e1ed486ae3897e63ab3e2268435eaf"
os = "windows"

    [[Enzyme.download]]
    sha256 = "280786c132a1b8de97d709722cf08c9455611fff3e8f4df502cfb3a0fb0211c6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8af33b5bb1224ac2f192c37e95bb2f4c69d03fe"
os = "windows"

    [[Enzyme.download]]
    sha256 = "9bb604d707d3fca5abfb4812023157910274146f155bb9c6e61ccfb7752a01b6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "edf1496eabd8ec9a7b55db611d95e23ef40b3fcc"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "664b66c9d0d6802370ec6a5781cae2489ac9aa46794fd91ec3cc68c31abcb5ef"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c3668782fdd78b79ab46e6d0c91376ddd7c3ae8"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "c265209fbc262f2d9d9325bffe6db7609a7bc0d8d35e488440c2a0d37adac9a0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "de8f157b7e6ac2a9d0ce542f7fb41a47024cfc96"
os = "macos"

    [[Enzyme.download]]
    sha256 = "07508318b8d92cdead6abc3b86cdf0bd2f5216e043fee35b4c5fc1bcff714c10"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "981d769fa55270c30834f2dc0260c067e655dbfb"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "f6aeb160d6e52cd0d6bf665acd6b4754cf4fa93d2eee6b0b1b4ae3d76dae65d0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3826095f5dc104df6763670ef1ccb1ceb031ab84"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5e7660d93e6c886eb2fa7b7dfc1b706ce9137a0ae0b69f3c4233a1e4fb24d379"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbd175155e1b7e1d27eadd136c9d3be9b490c83f"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "0ab6f0e76a065ff16106dc38f4882b95fc4fb86d4e0515e188c61907228655c1"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef06728593d780811e1593baf1be867fda67b7ff"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "fc8a0485740875caec756fa5b08a99a49099390281432ca15efa78afedbf60ef"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "581ed023d20696987435f42a326a817d6ef83c4f"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "81dab5604219cb19ae436e8a5c6659031eecbd8467c5a4e10713956af7f2c8ba"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f34a451d7964dc92c1bb06fb42038f7ca51b26f"
os = "windows"

    [[Enzyme.download]]
    sha256 = "5556900e07bed08c097d5eac462d51232602d3561da48a735489517dcc5d8b4e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69702764bf9e7e4c8016b6471d2836485c4ff698"
os = "windows"

    [[Enzyme.download]]
    sha256 = "cb3af885335f1beb7fa89ce1cedb849344e04e3ce08635311fc06da75d325408"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.4+0/Enzyme.v0.0.4.x86_64-w64-mingw32-cxx11.tar.gz"
