[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "374fd154296aeb3d35d7f8736e58b1925cacc83a"
os = "macos"

    [[Enzyme.download]]
    sha256 = "f125b28f23847026111b76c2569194ef9855f3913c39347d0c1f1e59603a2431"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "f6b01e7c7e07b380c67a77509d150393a4076d78"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "8c103953f4c5f61a96b5a3714c7de7a005a8d6003ed48ea7132e26f26c569b27"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46ee853b91ae18c2fb93109b8b77af34583d97a6"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "977a58131fbc912f3d81bdb0e1fe666fc00743510aa5498669ccc1623f4b56c8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3035246c2d041a23899bbc9e2128d7b9ba698093"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "619b56088495da836837f3cafdf416fc9faf8353e5e4cfe81c776d9e85485c6b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7c80417b24de93ff26ee1f1f38f67922ddbd187"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "312cd277c1f5e1cdfec5bfd0291961bdb4e842363292ce4331c6756110920951"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16bf2a86f17ae6f1c8839161ea4aef39e97f6d61"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e41ea8f49687f98746f5c4e0baad4c0369dcbe9507d92d1f0dd297dec03dbf34"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cca37ac996312acc69461b2ea15d9b0086413ba"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "09f43bba20651fbd60acfe6683a0701dc6d2262a99e8611d56c23c7d1adbdf8c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae6de07de9604da29bf80666efef526cfa06d50d"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "2855c503d044bec0256567a38293d1965213c5c9c4aa64bfbdbfd1bdc846720f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87e0b61147bf33991ea535ab48fa49f35c117312"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "12c319602c81c6c3a3c0cf6141f514fd02c7af5127613138393081c0ac33a30c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e036bb11db20f3c43ca5391612644deb74a2ece"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "9e05cba4703f54de4ceda5d78cd2f3a3b0b5d25dfbde58cf90c4fafdc631dd9f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7d9e7f52e9dc61ec56c5e232d7862eb24875658"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "2f63f25010bd36f1aebffa66b348c9862ca6bf8ce03adf7f3aa338ad7afd2c57"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29ad37c581f0c822d722821b26d5dee20b5e0321"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "53228d3e60f710e1c8a1705c000a62cd1a74fb6ebcbd29ccd9a46c7afa6e6b47"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "057e6d6e96d161836758e5d97b186bcb908ad09e"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "c06def1cb6e3824f0b6e38797df2bfc6e4c435449f93a8eede0ce8923bf518ef"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c400d5381d67e8b2acb2abc3f26775bd759b71dd"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "bfcaa06c7c8eabc792f760c1275aabaa8d7f01b7716a304546c3363145a02857"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a92e24f7c3ade9ea855aca246ac5d49e9bbffab2"
os = "windows"

    [[Enzyme.download]]
    sha256 = "140da10de6e89554a4668c0d007fd850bff574d7f41c1b37eb1a9bd6dcf4e780"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "747255c24756fcdcf04dc466150f23c36fd54aba"
os = "windows"

    [[Enzyme.download]]
    sha256 = "3167e5a43978955c4d9c2ebae8f45f04b1649c467eed3223cd0fcea58edddd5f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8692259b30232bf09c1e668375e5466887d8af4"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "4d848f9a93a4d497ebd027155c5c32a4a0b1f7ade72a79d1446ca6dd90cbf24c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "169c37a006c8b8f6dc158d072ae6be4e0112aa1f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1d32f9a39ed85be87de4014e36de62337d93b6c4a4e45aa38586a3f686a4ad81"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0016acc498068d5547961972d811b6b6d2f8253a"
os = "macos"

    [[Enzyme.download]]
    sha256 = "b5c57269948c0a85ad94ee55db4b7fcd9f9212352f9d2751c62e5bb0c9beb1e4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66ee5932595c485add42fd7ed51164b3afb2b7e0"
os = "macos"

    [[Enzyme.download]]
    sha256 = "552bc982e2f74f6393bf13ef014b46e63d468443a36f5ff51c99cb9951a98f93"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02d7b28dca1174722130815a719bdb74af0e0edb"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "cec4c74be2f0137567b8434f77112c137e50fc6beeaaabcf25b9ad10ee1f0d4a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3090aa2539825cfb3f51c989bf06f3a6e3f3d8d"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "717a75ccba78c0704d70e95dd4af8948d7ca17672221463c91bea6bee62e124d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdd8b8ed43bfabca093c842786aee0652f12b4a2"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "8e1edb5b7ae78fb25370f9515fb52d795344e2b35de6a07a956b083df3afabfc"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00e2b8543429115c5d231408994d6be6fe649ffa"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d6a4f2ebc9a2d27f42bc53728c55fa57765f719b322abc07f559f34632bdb0eb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21f78941c197fa5e69c8678645c250c7bef7660d"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "5390d8a24726aa502d9a4c99bad1445de298c646554313c2d5bddbf8c5867430"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1143165e6557e64567da3bcffdba033c4d1d99d"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "26c829b59586f3bd54d0761452e949c5c6ef608ef321ad830f7526da1e48b65c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61c90d1ed88f61f7d044b518b409b100b7368904"
os = "windows"

    [[Enzyme.download]]
    sha256 = "b3a250d0bcd31a57a86484562453ed053d4435f3e4df0528491cfae4ee4bde84"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3f730c15b77cc4bc57c5f4a6d59643797629bd1"
os = "windows"

    [[Enzyme.download]]
    sha256 = "57bf24a718d17296ab8c28b09d632ca9f6c462802eb9c18ec303576b5a01584d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
