[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60f9e5a6b9dc9c62161ba1bd427664675dc62ad0"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "272393efa73e03d1f2fc1bccc54cc6e16737eceeaf72489e51f9db2e76a15a3e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2085ca4594bdb1c91b5ecb0ba56d037e1e416c47"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "dd43d33668ff216e86db8177da332aba260fc038a3d77c1b1d2837ea247af8b0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8747bc8a7718e109cb5fe150cf20a7bd428f544b"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "2d1d7366eec5ed06d78f16ceaaa0373f42ac43686410026c39774005f0f5a2e4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "721d8a9628abee8d11029fda2c6af1216051b543"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5ff148ccecdfe6a1a2e260e56930aaca9264f8e601566d9cd5f9c9a899dc7ec8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34e8f1bed95bd49f338a8f9b77dc0efdae6b57cd"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e70dbf9a7bb0521be8670510596cac91e30665f833241062a2f72132cc7e198e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5209e3415ea43e6bf6e31d81fc78abed4b63bdbe"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "177eef37be8d0b4ac37f82105c389a273e09cdcf17d7cc35cac64091e18f6e62"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec90ccf288d8960d6916a14cf33a00f64b12d3a0"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1c018c3a881e2cc98737f910e45e64232a3a378678ee400f44d573fbbbe123fc"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb059bdc217afe8be8a114bb37f2c5bbf3d94e90"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "0647b045fcfbce93357ae0ac8e0f91dc4871ff5c811db2c1b8a44c25568295ae"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c88792a36815d9eacbee56aecd8c3b6d1d3e6b1"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5b8765d65efa0f7286ec6ff0d70e27253e7e4d350734df98a2cad54d1070ae84"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd71f6446a4be53f9014d13df62610adbeb7fa4d"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d9485ab610ce0d75ce2ab4404f646dfa797bdcfc5053cce70de3a71dc8511953"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb3eefa7622eb8d5b06caf3cab106c9dac7c9de8"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "2a174d05beb84e4de455c70501b1aa541928f09ee110ed6f2b5b7a9be26be51c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20e7ebe98c429972a69ce138b020ebad3cc2968e"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "bf69ba78b557880d7b75f14e6be5e2aefcbe66a1c12244f662fe7f7e4fb23d92"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34e76f3927c0602b908a22741f7e95298b460137"
os = "windows"

    [[Enzyme.download]]
    sha256 = "606412d98a8baec6f30e47652bd6c242c80c613a2ea341aed27bcca21aa8ff54"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb653700ea276d847b184786ccb73c5590158950"
os = "windows"

    [[Enzyme.download]]
    sha256 = "13d003f117c982e15e2e0bd66183ee05a85a81cb126e019f6ff1be7d562ce653"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53786f35cd9aeee263e1116ed0b54a5f55f6e0cd"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e8ef51ea235b55b13d06e81fec45fbd3b747bded4ff05fff57053527acffe761"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd4224ba482da09f8c6518add991693de1515c40"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "52bb69ca522b5a8befa3cb6681d17e6f4d2963ab276ea9b1223c86c325439f11"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "1d3a20ba379dfa42d920b30f17ede8972203be09"
os = "macos"

    [[Enzyme.download]]
    sha256 = "7ab1daee73ad956dbc004c6f7b56e0e085aa7eb241a80d089385facf6eea7f87"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f45b3a0e63c8dbd92c05d1d4a50bf72eed419c0b"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ee8f0e4329a18cafa1444d9fd74ee9d0b7979aed03b42be7cb9e8ac71303529a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfd90027f4a92264bf5d7f2315c72ecb34e25ff7"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "3a5462cd879e641f283a55cfa881ff310800f78f6070554f23417cee3c6a9df8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe3190130f255cf81d3bceb3ebbd4bca5cad9f83"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "0942a818488b76fa6774ca487e6ac059c1347d22b2b199da879d96b6a0e9e223"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f4e8916e589b332430369f8a6ad02b70a9adc04"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "339992ebed049bd656da3240ea407eb21b227f0158e4a892f46f1e271aff2425"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "38542e83dcf1276f2e96589cc1bf04af971c6d17"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "adf449d2cef177935c42a3fa59eb10126c4f44827567e8b129aa08efc76caf4c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41770e6e87f95e0cfcb6a868409c6faf2aef0398"
os = "windows"

    [[Enzyme.download]]
    sha256 = "3c46130b892021c28f8afe376c3b5f7d7e79af859d3aeabcb043c379e75edbd1"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43e253d67d7f94973e045743af52a25ef278a017"
os = "windows"

    [[Enzyme.download]]
    sha256 = "f2bcc926cdf408a66500a37568e22d30d80a5427e21f7d77970bb09346c2b75a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.10+0/Enzyme.v0.0.10.x86_64-w64-mingw32-cxx11.tar.gz"
