[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6ef799544ca5c4e43c743c7efacd0cd7e97c153"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d49a80603673ead6104775bbc7fb33e24e29a2a046de03b442fae592c87c9d61"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e40bf21fdc4172b42c1089bbcb2d724abdc1946b"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "707f286112cfd16ed29016782d0c797bece4165a56b0d224a3ba94ac1f5766cc"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7470cb8203af45b5e4509aa1c030e978002409e"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d17b01f76e49395a0bd28971c79c747bc670067c47e3a91140fcd93ace3030a5"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "464afaaa1311ebf32fabeb96f8fffb9f21a51b4a"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e2588e7a853b52a4773f40754c7ba1c95527e570f8bbfd77886dbfbfb6b1fe45"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5563ed20e6bebcfb2c6bc2f67e24c45afda4123"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "fd90e9396a0833220846907f2779093b9b9bdeb370b676fb4f85e3722624d9df"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a3a1505da3cea9fe3df6538e80a21aa2f5d69c5"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "45402db7bcd6e70ddfb5c59b3f292699be0b6f2ecb82da41c17a2dff948ee8f9"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2ac98cde38cd729203b157714ad762ae6a1d5eb"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d341540ff9cd41d5fc057d505c0e145e4228d99b89a4a4d23366d096cc097701"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f264106da427a7d08a88327b73e7d64c3e4b9274"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5e4572ad808c83a2338ff4a830e05a44082ffea54944d1d79a552ec126580fb3"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99db92b19afa8146432e8eab670db6854f71d5b5"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "b8f50387d80cedbc835f5cef4fd5d212c2ca3d890f220094894acd12b5679ed1"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03e0eb78cfbd65f1d00cd71cb2c56be6686103e5"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "749f7db937110a76900f13d636d1f01a6c586d499d205631f93773a85e74e5c9"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6d79bae833ab6cf2d21f1930e686aba220cbb46"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "473029bce22ef992701eaa4d9dabc1a4f6723871ab49f298900808473c2effeb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "695e79fac278b6a6bb3f818add42d1e15d9b3474"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "97b88620ca3c6a97a7d96f5ae5f72ae1551537bc114e23cd589bd8780317caad"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a271b8f3dbbabc740204ba3bdcfc88c4652c4ddf"
os = "windows"

    [[Enzyme.download]]
    sha256 = "0125cbc8cf68a7b85a282a4a1c7df496963b375bf5f47d3bb278c896c4e34218"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8850704ccff00f9ba11fb6273bc143ff5a94d1a9"
os = "windows"

    [[Enzyme.download]]
    sha256 = "8b3476f522340b7048a5899342820130c71dcbf13b7ed08533e391951c0cf0ad"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f9f81c787b80bb7bdbe472c1715b77478b88aee"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "f0bf3fc68e06b137d52c8321c9c57b5829745e581e8d140e06ca1b531545e046"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f348821ecbd8a17588868265358ba1c474b454f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "a4a2afa2bf76e074c1abe9988eca1b1ec505fbb43b43ffcc4e02f4364593b39d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "dfc34d3bfb702afa5d46653d5ae68d0ecf4bbdce"
os = "macos"

    [[Enzyme.download]]
    sha256 = "113af1c8b36ca8fe3be44d9c297f05d957ee86812801a9142aa3ed5763999c3c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adafc9a40768aede91009874db2df20fa1f27129"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ea84afc80764c819bd54014a6ebf5ca6b78c4bccdce16d1434854f438ea98778"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e3b2921e2fe52a14eb022e6b43687902cdd30f1"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d1b922185627f61e80600778707311a5ed4bd90d637cfa0f7ac6eab2710725a0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2da16c0f3731c978054742698b3bb13eaadb9a5c"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5a44d6a7b5ade0d0da481ccf3eedd97c5fbc19e805edf4577e5685f3109f8a83"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bca0654be3ef1ce2d610eca84e05c775fa4ec7e1"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5ccfb7ffb39451a26569b6fd323e1cd52a826599e98b9b2ade9845d23f3c7034"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "6c2157e0cee9fc1d110693b702b7f695cb963c9b"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "572932892e5e9c0ce10b3812ef24734a911df03a5eec712973b32785badbac5b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f50a8918139d7f3a955f8f4222185843ceb08ef6"
os = "windows"

    [[Enzyme.download]]
    sha256 = "8750b8f852aeb1927d0318dad115873bcb623337f21e5018cd941a1eea5218e5"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a12de2595cd514ca0816bfba32fd370d1b2b67c8"
os = "windows"

    [[Enzyme.download]]
    sha256 = "dd47cc1d16a57af02260ecdda47a7c4e4cf2790c1bccff55218f09818e8e1c84"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.11+0/Enzyme.v0.0.11.x86_64-w64-mingw32-cxx11.tar.gz"
