[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a6782cd8b186935a42a7e0bcb1a3f93e3f3c981"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e1d38abed09ba87aafc09618d1ab2bd52f04c31fb1bfd284e9f9cdf7d929ea4f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2626b87b86b07b4d9722167fa9129aa3fbb0c21"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "7ec6e686915237a4519f889946b2adebfee75d670b22742a03f740525ce313e4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6c985a7f8b9d04032b3c29a735b8a6bbc32c543"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "539c4ed193c9841883c55bdbee5a2a250a2ef44cc76a132d9c5aac9a4fdf7b26"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4b0bf9eedbf86ca8c129f33499e9ed01a2ad8e1"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "63d4280b085d1013872c59dd60e557478d6b8cb0ae0339134723fd0d283d8e4a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b86051dcf55fe432738a6ffc03525c52a670f0f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "07a52122e56602414357cb86e92f2be12736a58048c57043ddf886f2ca1b53e4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "105515bd9ca7bdacfe8c277e299f67bea425fb84"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "9858ff94e94a3b2e507db61f397ce9258211c84d4caaca7a2b0460ca0a510b7e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45bb72d76a81e6af06a94a39e35d2c219383c370"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "6b2a99945a3c4fdc672034ab37fcc5344b6d696100f17949da0550bee9f730ae"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a1f6a7498d32c5e3a6b88840b3a7481e52e6dad"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "3fc68b1c48a2cebf866f8fe401bafdf2e309440db53ca9a36248ca319c191483"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "165906ea57873bffaaafa32836e979cca797a42f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1173c11aec10a47a733ea79490d9479d31e2cdd0540a873412b3a1d82215ef6b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67ddcf17b4e912d31165a178fa3a2a57ce48b01d"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e9e849c0d731bb6159b9ed8bd96a9d945ca0b8711314c9e6cc7d7d89c0fb8119"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd44d56225d721bc804b8777b1e9db323b1d866e"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "59d6f479dbef07c949eb72551901781761f2df326ff52254a0f46bca2da1dd29"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7887816619b3d19137ffde869eab9246f28b3fc"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5a4784037f1ed1b7bf495873a8aebd4aa638d71d45f609c0ae07d1bf84dcf6cb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34a2106cd45ed463ad3a3ee30c0e3b9a338fe97f"
os = "windows"

    [[Enzyme.download]]
    sha256 = "a5e0ac2316d61840f43e7b781d469147e12a997da97e514d6ead93a0c98fe611"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1f2dfbadc11033cab1f6212459f73de400dc397"
os = "windows"

    [[Enzyme.download]]
    sha256 = "2ece2bdedd8bf5ffb579121aa06a24b726952977ed4e63fdef94580e146e8817"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bcbb8c2b392d4b4c347d83718a8d0b628e9ceaef"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "dded8cbe17a8e5e22367f7e58031955e7885dc94442c9639f09b5eef1c9d064b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb2999e1092c0605f5d292d9538e006927505a80"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "32ca5ac5395b91524049c85dd4a38dd5d408f3619c30f01f047cab29397f9710"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "5dd9a9ec0a7196987d9ccc64f16ac154c08021a6"
os = "macos"

    [[Enzyme.download]]
    sha256 = "0573fe8daa53fd954fd010d75dec7d65ed8c374505e39ed6c69501bb3dc2def6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6fb4722cbf04a98509dfe5ed0727033134896633"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "449c95f10ff90f254b70bcc259824efe91c56a92206959237064ecdac9c048e5"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc948f684eb2478ba41d61e88b01e019872a0b61"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "c9cd3f3e00a5c399f553451a7ded4f64efe96b6a1b9823c03e445da293f013dd"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c09363991366358e7e8ef72b41a8fb21649b49c"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "15b4f604b063ec7d46aa66256630dc8cf77fe0157475ba5e5dadf904e9889acc"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e80af30211f82631607b39d2c71b18ff46202c3"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "58fdbd5edf742d2ef66fdc492aef43404ee5c4255b441abe3f35b4f6b7de3e17"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "fb19879efe28c4745049b0c2162fcbb5ecd133c1"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "474cb5b07ac2c3d73122648dda033226201b542b731cd43710eece0af71cd99b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53c3197fb34d064fc3a28028b434659c1e873591"
os = "windows"

    [[Enzyme.download]]
    sha256 = "28ec1463552f0008fd3cb69b0bcec6487c827841c4a0139f0bdfbbbff705aa65"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd34595a25023b44fd4f798ac8df70da97819b4d"
os = "windows"

    [[Enzyme.download]]
    sha256 = "a31bc769c01431d4f8a85356b6c60904b2d53c1d153088a2c011b8e77bcd6e86"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.2+0/Enzyme.v0.0.2.x86_64-w64-mingw32-cxx11.tar.gz"
