[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3cd9bc27942a95fdc3143e5ed76a3a48f2595bbf"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e2c34a0e785c6d8cebd3db95412af6ad3dce2b45e57f1681c59f550ac0eae0f4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78872ea9ff673f42eec3e21ac18489afd86df3b4"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ea47c75c824a682afeaf8d221d893879dbc0bde8b2d3463eac4eca63bb20c196"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "173a27206dc998dc78632c40549ef0ee1e2f766c"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "62a8a4e9df9fa63ad8e085cdb29a1c5a2b7ee04d77aaaf027350b3c807d0819e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b15737c197d65dca1f3887f02624e704b84e835"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "909bce8c660ac6b06558373de3fd819594266983f7295c5086b6aaeec973c8de"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46c193428a3ca78502ae348cafe8a741761120d6"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e40b3082732e5632f65d56f2e614763dad90b1734af3599b2eca3cdf1fba6f9a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b964b77f101d38c0fd71f322aa157ff711e17b8c"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "3fd657e8d23e54c938d2ab2fcec34ffee9662ed82d66a005b3d3a0e532e0d932"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c63ee52b70eb74619199450d54d16114e642e35a"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "8b65da7a5a1db1bf42347dbdc752b588a825fe2c357a7d49de672599785c05bd"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddadbc14cf8b4f78002ecd76f8158324540e0e55"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "aedf3b4526f9a0c1aa4a0a7644b441278d055ee80e99104db167f2b7b40038df"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ba85d7ee8445648e89e327822b45957d892ecad"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "3d15726b33e49b20809429642478288e41ce90787016034bc935825d029e23c0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "718f31e8c8e79a9f63403f54892692a6ba4b377c"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "070ff6284d4e8e8f4ba5aaacb610454c6748d68bfffec19862c3a2f647c5f9eb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b278dc91a9039f0ef49aa66ff2df70c0854331b"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "7a853757ce00e4b9063015af53af788fed74583f2c1eda49a97eaa0db9dc1117"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1158f2ea9a7b7156576dcb52cad46b65eeaa0e3"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "bed8d8f323dfde185125e56cc3804d89016c2da5fb759f5073c64cf95256ced6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c51687d3eeae88db00e15eca67ac278dbe09220"
os = "windows"

    [[Enzyme.download]]
    sha256 = "978735a241c494831a3e203a65141da8d9221d2099e52b475dbf099073073081"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cff42404d8cdea0a7125cb8cb86eea60583bf345"
os = "windows"

    [[Enzyme.download]]
    sha256 = "0df3818ab6bd2238a9c27d265449efb01bd61d6bd15dfcfecd28ab1da5e38afa"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd18f76f41215fbcf9e2df8c69739420a7adaa8d"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "99075ab32673b67da1119c78e528cb637b0f36a9888da209b4eb3b7703d1c9c9"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e3deb920d34abeb7d916648f3d42c4d7376a896"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5b3fdd8204feb6da2597b01ad8df8b63e2d2ca3e98c525b5f591dcdd9d403941"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "9f5a4e2a55b80bf11066ccd65478bb1df36203f3"
os = "macos"

    [[Enzyme.download]]
    sha256 = "e49dbc359fc16f278c1196c10e9ada3a521179b1960379727ca165ac155029a7"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee52cb68bb3b27a6f5357bcb108d2667765a20c1"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5ef4dcd9f23c9963293da47103bdd613f8a292bedcf6611ddd08344065049f1f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19c683219da2cd3368be22119df2e879d1d7489f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "9093adccfc389b78470d94e2493ebb3ae2c312916ea9619b235d31c79f0d4ade"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb24a6d9ee94c4d08a9869e2f5f53b6ea2d89bdc"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e4e4ff416abc7d4763e194051a8ba0f72f994c1c73f979a6a997ed3c783bc0b5"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e500d757e68aa71e9b46c7922583b0d2196122f"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "f7094ea580ef52a9ef91827b0f1945ebc3c7db34becfb6b6686c8bd252ef427e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "22be2b9545c7d46ed1ea26f40e68dd8442678cad"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "6456add871bbca99e00f85723f9f473455a12cb54e47f65b4016a7268c28884d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f47781824b4a5b5ec666967f7ad12c9a5083bf9f"
os = "windows"

    [[Enzyme.download]]
    sha256 = "2ee9489c41f63c96b9cf191affc5748ff6d425e324662c26d580755b229900a4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "278d95f5633e89f3b9d27b1a18705b5e07273509"
os = "windows"

    [[Enzyme.download]]
    sha256 = "b9d5c47964c35fe50465edd63074bb633f25fa041080ac8528540732819c251d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.3+0/Enzyme.v0.0.3.x86_64-w64-mingw32-cxx11.tar.gz"
