[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e444ffeacd5d2940c072fc9d614217591d4b344"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "db867dbe1c5f4a5d5b5a00bd0cfee41c3b76d39eebc3349064f1542906378815"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de394d86a4b44c1bc479451d1727e10a42b3a871"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ca5462ef772c5c7ee68575d5b56b229ad5f0325bb4bdacba700d1d13c7d14836"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68b4b3a0676930a44cbce85757e68d82b3a11f16"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "0db82d222d4f976bc015d7c1f3d4b0af8c41a21f4318a234122e3cca793363aa"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12fba8aa40256ac50c8e91f707d36c55e77fb89c"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "86b6e9ad8ede65d5779d4a3b71f3eaa1bb22b687b49e62188a23fc2507ba4f3f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50410da9d9a6f7ab7d46a4bddf43f24b669040c1"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e1bc464afd7f27a2cff2474fb34f608440188e77e19721735bbaff2b0142fe62"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c09bee62c911e97698e3a643101148d6364a4f72"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e00f7f82f2fd5becfd11a7c97fcff5180d453090433fddf33c0050ac3e70f7d3"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cae8c71ef0efea8a9fe12838ef7627ac7489d3f2"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "c55dfae58a7930dc597d5aad33157deb3524b01e1204a3cf87de7876c6c11622"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3223e02097dd2f9fd4087c4986c694ab3d0122fb"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d8533f0f75ecf12775c294658312c588f2664c22dbc4d209b123d3a0fab1e9dd"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52601e450815c3f432fb977f751312142eb8f3e7"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "75d471531a94a610ab1ad60c64ba98fe9501c2875f434624b8d210289feffac3"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6188d17694a6d1c4ed8f03b4a85bd89f794e9a6"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "806938665e9bac6622e2b7f4109780e280db553a896a864b5038854014b9532d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "155ad874ef804fc8c8c90123a7b1bbb2706d32de"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "50f15a386c447286acbd8a54adf9a1824b581d5f5f00e26e82fd524c9e39e4cb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "048b42d006d5f42ead865b2fab9cb6797fc707a2"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "a1f8c3b09086384dc90e57d2790cc343979ebe92be9ab7cd3a64928189adeea8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35fc358fa50f7f88926afa5b31ac76854b6c3062"
os = "windows"

    [[Enzyme.download]]
    sha256 = "2b04cdd5029258118545b03735c3bc361c7d5a95961eda3b09841036ed4dabcb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9252233da2bbaecbcf2570a08fe8c1ef4dab73d"
os = "windows"

    [[Enzyme.download]]
    sha256 = "b7ae48244c4bbb06f076fe07f8d1a87950ddb28b81d33b5b48d9cc1df8ecc409"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc04443585f62dbee6830bf693ef542cb9ae5fd7"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d5aff6abf92a72fe9a4018999f93efa00631fea7df659498260bab5ea5837356"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bc9d1f8df4c60cc329c1dd8561a28316e1df5d8"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "3158ab6f7a56f184583a3ba8c5979282adfc21d33cc9e6175993df8b02db8b56"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "374fd154296aeb3d35d7f8736e58b1925cacc83a"
os = "macos"

    [[Enzyme.download]]
    sha256 = "f125b28f23847026111b76c2569194ef9855f3913c39347d0c1f1e59603a2431"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e79d09ec8e728e608b13176bc75487c96f42571b"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "52fa17fd761842223bab69e20a6e6a74a3eb262c54c6e871d951f97240045564"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a671d44e3c20e5827ad9249a0b185fd307367fd"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "4acdcb9a5ffa0ee67007d1fb13ba0eaf0e8f302bbbddb46083fc6010cab64b4b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "411e9dd816ca274f910e398bb9c82e291003290b"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "eab2eb049e4bcdc6d10f127987f933beb2ea7342046eccb87c6a270e630d39d3"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "882be225cc8e02a6e6a4d5ac17621bef3ad92290"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "7b23d888fc71d9e3666a8dad4f694a5ce2bb7b08f404ed5f19fdb302f19ba635"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "f6b01e7c7e07b380c67a77509d150393a4076d78"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "8c103953f4c5f61a96b5a3714c7de7a005a8d6003ed48ea7132e26f26c569b27"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c20af356de0acfee8eec6726a62105fefa7c614"
os = "windows"

    [[Enzyme.download]]
    sha256 = "ff20865dbecfb90684ba7da846a44849d8735eea5c4d5078c8eb058ad9730647"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bffb3d75ae4a7a6d79f28798521417a40f203d5"
os = "windows"

    [[Enzyme.download]]
    sha256 = "e8925963575a982cc386ae434997f07ece101b7708133a34fd35654525b1618c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+0/Enzyme.v0.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
