[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0016acc498068d5547961972d811b6b6d2f8253a"
os = "macos"

    [[Enzyme.download]]
    sha256 = "b5c57269948c0a85ad94ee55db4b7fcd9f9212352f9d2751c62e5bb0c9beb1e4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66ee5932595c485add42fd7ed51164b3afb2b7e0"
os = "macos"

    [[Enzyme.download]]
    sha256 = "552bc982e2f74f6393bf13ef014b46e63d468443a36f5ff51c99cb9951a98f93"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21f78941c197fa5e69c8678645c250c7bef7660d"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "5390d8a24726aa502d9a4c99bad1445de298c646554313c2d5bddbf8c5867430"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1143165e6557e64567da3bcffdba033c4d1d99d"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "26c829b59586f3bd54d0761452e949c5c6ef608ef321ad830f7526da1e48b65c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+2/Enzyme.v0.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c75c0963b670e8c98919af2d3d73562f4899b63a"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "f69478d02a904de992787b3bc8f68d575eb1ea3b538e9b448af39dda45d375d9"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3095fa8e7c798c47d9dd15e0b9d2dfac64ecc78"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d53635e3de0e10d5994b8c90ffe0fd211a512bc73f21b1fb3f8777c1bb0838f5"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2b745c21c02bbabe6ae85f8cc062976beddc7c6"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d76f7494af5e4752d0802003189d572d2fc53d0e8c4a278d3437fd43c8a83e57"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c9707dd41d75f1ee09a173cf4458dc911b0db31"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "7d43f99326947b83bcb941b91d63c09aa02e95c61a2ea4e38c6369c9cc4b4522"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88abf7a3344f208785cdb6e90be98efd33849cf8"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "bc7d0a97a4e0c74b5612fdb5b947713132b177ac90d6d7b6eb19b5e30f223c04"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ec3e8c118175f5f38e8ac3be3544c52af1da10b"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "9d9fa975c5d06a806cd5158ccce2cd359af0d5c0b518c7671e0cc3cc6d291fef"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2608bdf5486fa20b94b30a68e95b5ac285ac5ec5"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1babff4fe774a136e1e19c44683032c7bac2ebbd93a61bbe074c44a407a75b93"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97f5f2d32975f162bc82e340975cc36d0b64780e"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "7a210bab9899b573ba449be9c7d63aef7aca84fa7c6af0116ffd9f836bb410ce"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1218d8c3bf3ee706251c23abe95299a1c50e31c3"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5c654c66fecacc62cc9e0415e96bb24789814bd8e190555e7ceb789b694e8c8c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f9b3aea164f648baa8393e9d9b521ee4ce78dca"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1cae8216a573e83ad176b8dd8cd1bee1446b0baa8e7ec6a9c0e8cbd5f8894ae4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbac3e16f1d54ccdd5605b638f672492b5e69108"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "c147c9b8320134d01469e4981e15109fb401eb829e77fe1f3bd55b7248344dad"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c28c1b07990d3ebe9bce6af9592e149f0db2a42f"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "b0bf8e43141e6b5607339ffa793ff770dc229cf7c1710c7c1b7d0d7e82ae4faa"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcf8cca45cf689e9bf9dcd2437e74fae20759cb4"
os = "windows"

    [[Enzyme.download]]
    sha256 = "cf8d41546c20a039e10f1f64abcf55705e2798ff49ced08bcfab3ef365c5fa72"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb145fbdc2d9b348a5afb10e33e9a2db7f0fdec5"
os = "windows"

    [[Enzyme.download]]
    sha256 = "6f2f5fcadf923c6d284fc8e16f8a59b18c61e682568b124c1c8081981b617155"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "161bcd3c4e96361215535fefa442c089df99c3ba"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "96413280a557280df5c7ae0d483dc3ddb86160f44e7d21a7a8536658c35065d8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59108100a02a6f88e9eb74cb803e75e39111e821"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "7c0eddbd835fb023fb46d3d5db4b130111cb13512e84f1bb596fd1efe28034a2"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "41c87e5df49552aaf7881cb2f9f0a9af7b2f9a97"
os = "macos"

    [[Enzyme.download]]
    sha256 = "a2a499be2906684260506b2280f49dfcac61ea3ab3e9b1417b87b9d57330e5da"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "646c3884edb9b22ba66917e22fab0cd9db1c83b0"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ad83e649cf0dc0140f61986d7720e8c1e7c3e84b29d9a2f10120b4ed72e9308d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7247ed4cbb5d3cbe28561cb9c316e52407a203d"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "cb5f3eda5f16c736be2e04f562985a2eb08905555b14894022beed06f177fe27"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d495c15a435a1dee41942e7b534e7da247067703"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "dbd219ee1085ac162cbcc95e5b3f8a44a2305fecfc271f098243215d2d9fe1af"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3b11ec611d7ae463cf57d976ebb0f63f31c487d"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "cbc172c55e00ef21936ab097038484404fe959bbfc341840951bd06a5874ea83"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "8f4147d9a254ef2a30452cb116e35f2e1e765d67"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "8d9820aa200e51a0c34db46fb1b40928a354db3322f002fbefc1190aa3fda0d4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9dd6b9f766114a89c914c5d474ed7a045ae64246"
os = "windows"

    [[Enzyme.download]]
    sha256 = "43dd40b0003d4774afcf0ad2953c48e9984b100329ea87b13b18b4890e466d57"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f155d7624fa6b13e02baf80db75ed20bf3860d92"
os = "windows"

    [[Enzyme.download]]
    sha256 = "89e030504c689267cd4a8446c69f8277aee82d52e4577abc563d409b5a8b95de"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+3/Enzyme.v0.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
