[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3abc938d42022d1dd061681dd64a25284a22a586"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5c3513525b3e2ef9609bf7406069cb1d27da45dd6eeb3d3b7aba960edd9dc523"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed8c9fc6502806dc1709937471894e40307f82c4"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "7199efcd8f990f850a7bd34599142efd085a18ab6245560848066808643e4c0a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fe0fb69bc9ade52537a9d44b61d8db222011131"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "f1286d180d5c7d8a1e0c2f5ba7c234f8bcab3becc7eb14c8c3565e0c769f0a9b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a53a9df667f26157e1e375b45f445bc5d185f081"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "3de85ce675e657039e7c79ddb571320858b11f043583db3075f212348b7dafdd"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6be504383869769d2b79be10d23c686a5c9b49ba"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "a92684a077efd156364b376d99e53015eeb422e2cb211c8a399b333282f52caf"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0918593525d0a2f1dfe390e3dde5041d3631bdbc"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "8e4dc78fd37987ab0442ba7e3435af871c493a3d6ce8529010f4bd51c0fec46b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0f727f7fe9e6769acbb267f79b883f3ac979ecc"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "bd77dede82265a17925f23fcb7cd28fffcd3f3713d3b202c1b064fe81ad67dec"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7250c7cf11c1ef8a92dba5508da2213830589ea"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "8f0f5e28468b93a4946159e9968abe1571ccda15fc12802877c0c3e5b4b5e0e6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9880bdf864c82564f9a2f17500456e51bbecc2ba"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "6da080e996fa7a5ecea73c331337867160d61568c157ebb9229d93d496cc6f61"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bbabf7f82623f4e03551f70a59ef64a3e0f77fb"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "116f5b08f575eacdf90cf9534cd4a98dafae794299c1a47b19b4d51e0afbb00b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96db3684842442c0c328a07003269192b4da470b"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "71527a5e83aa4ca0784e7aca3c84a2712e5292c37394362b180b69a9a1114c24"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a38de9ffa1fb843b58c75a6d0f195c7f247e13cb"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "48a1a91ba4a19aaf31802b7ab52ed976455995ef4b2cd4ba101e6d07a8becd93"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ad674d75392949d904491d07a9cf068f07bfa9c"
os = "windows"

    [[Enzyme.download]]
    sha256 = "9610c9f7c27aa65ba2d5c233d18d2f169087c70973c790abb56ca1078a3ff0fc"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7c0383641ac15cab8db2c1320af670e43a0aaa7"
os = "windows"

    [[Enzyme.download]]
    sha256 = "05bc2ea9a6e1eeb262cafab73339c4e13a9b1253046482a66195956f02fbfdea"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9679c7ee4fbffd46f792881dada48531a830c37d"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "602e326312e5f382e5a30857ab735256b25b69290ec01535015b7f01cfcfc6ab"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dac3da5ea46751509e7081fcb095ca4d098f0368"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "8a542e7d2d1a061c5e0cadaccb8fd2b2c605d7c5a9644bdd2ead5581d3845bf8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "01e3df536ae9c5d5fe3bc3ae19d9ed519813cbf5"
os = "macos"

    [[Enzyme.download]]
    sha256 = "f7bacaefdefe444de79a34287e1304a2ea7b19eca884b0707dbf7f74ba3321b6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70d163275e47275d7c2d3b17a30556c443ca4c31"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "f8a55b190e5d2a614128059becca9f3b1a85e2ed3386c6a67b85b5552f6dd541"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "726c0ac769d38a301b3e0b77518859735a24ea1c"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "bbc11461261dcd038becb14e8f68021e5ee3f94cab7301706ab93006bb2033bf"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e990a9767b5a216d5b18a955fee45ce0133fb4e"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1651396b93c3af6be768429fdb2430f00798dd0ff4216be15bdd9070f63a2230"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0be1391dae1a0029e4be3c2771702836a3bcbfcb"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "28f77c9689a41b7ef8b6ab72c2462f3c71fa3dd5786312f3f4bc0acb1b370483"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "34385855bd2ae94f4f68477d959c7eefad8c8c6f"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "86b8990d1f13ca05bc9bb3db476e6ce95772120576fa07f657bc4a36c9856b9e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "911437a8a25ecb75d3ded10e2e35efcb0c7d7ba4"
os = "windows"

    [[Enzyme.download]]
    sha256 = "642561bca789d9c939d08a88274c364dc4db9555f8e013e68019f73d31fe5a54"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "868c581c32ea94ee2b03d4dd44801c96fce9ceff"
os = "windows"

    [[Enzyme.download]]
    sha256 = "44a8f643ec50ff0390f8fd916c1da4041041d4a93c02f23d23dd2c3b4193d165"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.13+0/Enzyme.v0.0.13.x86_64-w64-mingw32-cxx11.tar.gz"
