[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9cd6338619fe35448d3ad85475012094a3593730"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "7374e5b176a9b6d5a9fea72d2deab2ea8a20f3c15a3f499a0541c34e3c48fe39"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1cc83267c0133f65ba79eecc1447ad90471bc74"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "92f65a0a832eb414556ded0af806d66e1fa73e511362352ceb24508cb0f5036d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9261b9f6211eb4168737dd6bf2f83385ea923380"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "0ac401f503d26529f02e03fb6e6b5bc4ccd117315b7aaaa366418349538a8c48"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96f4c930b87e5623fb2f4db5014915ef47e0d9fb"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "c60045ca9ab0691c6bf3d4363fa8f29551b785abb8fe0c263fd9df8b9d3daae0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "739d9f4a2852ed8874016ba722c86cdda7286eaf"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ce1a8472e3d0772d4801ea90bcf266719498735acaf6b1b4a5c74df029788756"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5420b5c405dd648e883ba127cbdca27320204ba"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "254720dbb064564d778e63a50a0a564f504f94257137694071e8ba42c818170c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bd9f573ab63f0d43780f2153d7a41f5a4bb3bcb"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "c3ad67a488b5a7e8a097501238852115d97e1327f2b1b70aa1ef633663866235"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef5d01975f8b3bc78ea6ddbf50186620e53a0c87"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "4bcc9d4b9426201c2fc69f0e33b40a8a928e1fb2c71480702b89cbe648f241ce"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c2334f98f09ba77db711e5339636684b8600b05"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "57c9e84f5831b6a7b8fc333800e7ba8a2d4f996039f8dadc53f9e5428c885192"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c156291f4f1390106daa2c04399559d6b7681b9"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "86082bb11927cc011c3525bd5c2a24916bcaa547fa963c421b60c7941d6f4a9a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7e74959c4ae3153ac61524f6cf7552f7666e6cc"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "9823a4ca5396eb92d3047b4aa5f8a5ec514b5156af73e45d26b5b99bdedd7dcb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fbe176a7c780f40a26506dc3002c1658f732a72"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "12bc10ae894abaca50942cd0a9d66d6c35d2b354ae69321428935f577f7beb03"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adadbc3c75f29a235a6eb8f62232e0d28450b126"
os = "windows"

    [[Enzyme.download]]
    sha256 = "1746ab6a554decfbc9e5be998dd59d33a50181f47645724dcd9ae6c6f2bb5394"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c98b88eddad6338cd70abc5573129dae76d96a0"
os = "windows"

    [[Enzyme.download]]
    sha256 = "5bda2b4630a975f39779a04298b78b7f7033f35da65f188d808a432dde7d1f16"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8b4f7c39dc6ad1075a184d3fc0f7f7af74baff0"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "3467b4ceba8b4b9187d1720f34ee3b80c4a821e18d23b4896e968e532107b2e3"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f82a999b94fde673f6ac9318ef7ccbe181d279bd"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ae13025a1320578458b821013b7375312ff7fc27e6e6ed6cb8e6e1a0c1bb6ed8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "5d832f3e1dd05c176b2f197dc315b23c3df7ba55"
os = "macos"

    [[Enzyme.download]]
    sha256 = "f9b7ceb6fec0623272a15a7d1da088018e682c5deb14f465af624e4b374320af"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e2b0f0c2f41536bc4b01730b51e7a7b88bce79e"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "4abfcebf47b9e64807f7650fe14524d95bb2ed42da17f6f8a040a718d4dac985"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11224f12689f5c18db805eb3778d0e349ef0b166"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "4e620c7afb0b45c4da01675707b5c3fccaead32e268196e8cad66da2a494b97a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0302917c7aa36ebaccd7a42b58f439610736faa5"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "9721a50b88af66c85a1df6383cb363342117af5ae7a9291820f88386b4d8df25"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78c2006e673a8d676f8696bc769ac03170cbcffa"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "927c6d98181135b543468ea4e499f960348b0c65a7869b913d6548356a93d06c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "9993be473ce4e38621f1733ab6ce9d8cef847730"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "8ede6431c3d2c5c5ef7f4564b2578883e865e2e5ca46050dd54c7d9fd31b1be3"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ad64614c948dddddcced24caf012341a059fec4"
os = "windows"

    [[Enzyme.download]]
    sha256 = "9bf24f58796bf452996e87687b179091cbd6091c20bff674137a72d1378efbae"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d91d064ffaaabced0c0369468856cc795d79905"
os = "windows"

    [[Enzyme.download]]
    sha256 = "a2ea16de1281880d9c65da3b483f66c5ddaeba446c52a6b2ca6724dbb5c847fe"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.9+0/Enzyme.v0.0.9.x86_64-w64-mingw32-cxx11.tar.gz"
