[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a1bfbba840fc9c0c9cfb84559a36cfc4f4fa02d"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "25ba79919a10eb77692e8645f7076c29ddd4e629fd1e714dd631c4aa6bee3341"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5acbc79dd3ce34939b32b52a498284dab841ac45"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "000c6fba53a8c29fdd0f756dfafd19d843640a7e8e49ec2a1734a88ca2f47411"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66f1997c55609cf1ea0ccfaeeba9ad94a343c8a1"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "4cff4d432736417f804a398c8ff8ab70ef84d893a3d8206344469f7214adf1db"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "caf5f99cb669c15da9342fdfb1c9dc8dd6f7cafb"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "c8d2929469288a42ebcc88409bbba44aa25c487f1bead6e71bdbf60aab7fe70a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4200d5533a09059744ed7683c224d581ab858ab"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "03a56ac73e0d3c2531b55a815039a4dd16ce1b8daa0cd95145dd699d55751a98"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a6e878670827bfbeb21c2837ba2b1ee1d16d9c3"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d252cf1de32b94ab53d4705447cf7241ea296b4b140604bee5fb1915b883ebf2"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84218c747e0c6abc1449acd551676c90f4de24de"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "c60d378afd4dffdac1ac591b6d7031376a6729d0cda676986e9b312467c6a064"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "902b3ee377673f5124351f8896d4fef5d34cb742"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "340e9900a6ac053d6d6de49cd718f32100a38d10aaed5cd4687b3c00e79638ed"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7be956ea172184ebb3857d59126717c8f1ec5a7"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ff3c93616c6c32de514d4db3c45e4dc22ff441590a06cd2baa4cd74c66ce8889"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dce39dbd6fb5cb35e3a55710c80cd200e72d2e5"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1b5ea77a73d6145d775b07815fac5120bed35aa935629ac3bd15e393f9b61377"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0057380f4f31bcbd0ea453a2144e067e5a3b59c1"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "0ab090e7b3447ab5e5ffac2ab42e02fd982d445c9c39687888fe4ff7d1ab8ad4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fb00283598f871053392226e630cde4c18837ce"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "bdaf40f8efa6c76ae81df21c61a7eb289fbde94ac0ee32c907560d048e08272a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88e37f122e7036c11c44b315c337da458051fb3d"
os = "windows"

    [[Enzyme.download]]
    sha256 = "6159da9be0c87e605b0096f98c984f703692c7cc0f4796179e0424a1f14238b6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "287fd32bfead1954f55a7e593a24e25dba414aef"
os = "windows"

    [[Enzyme.download]]
    sha256 = "858637234403164fd546429391263dc2918782d5dc5bf406f76897356e2b2e6e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93d117237d1fe0cc25b1d57ac401ad0d46b41724"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "536588975cbb3174b5532f9865f57414bb972302e59b46c3d355e46872078dba"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d57504bb619547c9f23de0768878af468fdca1b"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "b70498b010ba8631beb8bf79a36b08b557046ec486f8df9f72dee1fd95bfd158"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "291765878dce2439e670778ecf68151727bf3398"
os = "macos"

    [[Enzyme.download]]
    sha256 = "72efcfd5a02f330e82d8a3ee977df7ba525d2f16741e0cd34573b3865f0c7ec0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcb2b467df85a0f5c9c88078e831f808a3de8da2"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "cd37c0a83366781d5655e184bf2f4db38319f0626281091f3a698220675ab9ec"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d44d6d2830d89346b6e4c8e04c224da6cde3271"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "6790edefab6b71575311014a8bef78c43c421b6e46f41625710965207128864a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcfd7083621e06d6fae9013235405614a113c936"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d2a8a443e1ddb65dfa10f941e8d88f6be1af1a80d9c1c0e49f4aa927d8d8473b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "078889b412d96c1ccfc6d5532a97d7f10f2c4b6c"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1a5c4442a4d8b931e6133178f4c3ee57780ffa43b0ccaa3e3dc030b7addb712a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "5cef712e6f596e9333362b1bf75c9115b5c6bd9a"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "94543d033a5cc9a19bdc83e4720f9dcb5590938d796ab84c07f4fa99c8b20568"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42790e80ff1f251b576aeda130fcee1aa7155f2d"
os = "windows"

    [[Enzyme.download]]
    sha256 = "126f37186ae17f86e67663fb178f8c80730768be1c2e1d1d5633b368950ff8db"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fe0db1c43d9c559101e95e368e2038ecc4dc4f6"
os = "windows"

    [[Enzyme.download]]
    sha256 = "98fcf74756d032437a670cb834228d90fe65f6bc9ae434316c94d7fd6b25374a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.7+0/Enzyme.v0.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
