[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2391c3200ccd8e6b68dbd63483c152d192badb5"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d00a296d85df875b6d0dfb334efc3ad8a47a3c83f9f5fbcd0a80f755546b6fab"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "092c3056a911ee5d4c8d88b730e3be890ce486c1"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "f985bd520435a6b7debee0ef215bbb2786fe55e610decd9bf7a9f94ffb29ab2a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e702d1393e03ec5f03c18ce6406c3fcd2d46158"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "323ed301005f319a40440c06b178d9a6cd44ed4d226a13307170a6ffd47de98d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f452992a20376158c3c994aa37adbae724bde630"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d829831fe9341346b328c4aa8abc0f4af09ee5973b013cb476fdfdb8d5740715"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb05dddc80fdf7f278604d1875b2cb121aaff74f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "9e868ab1b4272f3ecc56b9f2d551351d2f1c921bc8e40876efaac194a50feb6b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69dff518bf67f3ebfd877ee57e2d943c52e6f22f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "12bd290caf10b6eac9d8f2a6c3386879174ad566e12fd105a328099fed0c7bbb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f03f6f0350dd916e1affbe8703f903b1a2eb81fd"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "3dcc291c26c8aa1a7faaa29e4f8a6c69cb187f82ce69cb6666efa684aed7eee9"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6cc776470304dc1af6e62c771acd2a45ea1c94c"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "9177da7e33439b48a18cf25689911d91f90f95786d9c79df474f67efa3300e15"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a9b260acc73f34c515d0e63ba3665c44734bf15"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "deb6151f3a94060c48985203de383d9f09db6b748768fa6138c7d2f54425369f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ba98bf8fa17fa892bbeeb3134f42d4c236c27fe"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "b409b34f26678c4b4042569ae6d21c3dfc04aa1411bc3b70402dd9a1200c712d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8977699895a19e448ea14c553b92b29f28206e0a"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "98dc810863b508ce6bf5474b61e0f376db04a0cc8ff77b2199c17a2932f65069"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30b2bbb8071522001870c7b90cbeb06c43a2914a"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "0272a1561b344cf3bab65acbf11e6b009d35f7137f1bdae9d4ec85003ee33494"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f532b9ab0b0a6ee925f83b698d0f09eb2fcfa755"
os = "windows"

    [[Enzyme.download]]
    sha256 = "ed0e2f3adf3c0fbe17a302519a8ba1475dc4dc70f7304e62d3156da0f67a9079"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42a7a1a5052333846af2cffeb53ac9803573999a"
os = "windows"

    [[Enzyme.download]]
    sha256 = "392514061be61adfd7d63f5dacdaa9c6d10b3f884d4f08c94e0829f0a15fbba3"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8adb37ba757c73ef0b7f937c0710bfcfd0253af"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1b53fe272d2878a8ee0c708319caab448581655e0726e72321d9b08ba07f5ec1"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3119e02f860b5a311832db01975049ffe6efd236"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1b72b60a6683783ec01d5857ee40b1e94e542f78b0aeafea507e896d3f4d6d16"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "9bbb2a7258c48c56fecf7dace664221554c8264b"
os = "macos"

    [[Enzyme.download]]
    sha256 = "6e89a6834459ea5e2ef157f8b6f95df53996cdc2fdc555325cbba52e27f2d6b4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7520b35e7b3b0b6b7a798b3f7f548e4c63c1d0b5"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "aa130488490e71e552094eaadfe3cc487aaf91fbbaec17a222925678505d2f51"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b52cd058ce85e808ea6ed3c9007f613fa5774e54"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "47aeecbd79d90aeb51d74bcbd93e8eded2611e3432364baa78a6900a6a56c823"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d5bbb6b03d409fb5f2dfd08c888609a86ecad8f"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e4c0539c704203f31ea4ce6cd8a76542651b1a7890d74dd92c3278e2a1dc6358"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e309e86d7fe2f8a76be44da1d2ddf8cddb7b909e"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "0e04c28d0fe7da5d45bd01f0002d8716ef6a0ef00d35b2836b924925b44f32dd"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "2454959ad576d348b21224d5042e2ba343417434"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "d7bb0cac781c40aab7e95872f6816a089cbed33162e23d37b08089382f1ff3af"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eae35a5bb42564c049254f4f1ef15d26da70e2c7"
os = "windows"

    [[Enzyme.download]]
    sha256 = "8be7baccd51be4cfdaf8716011afba624f7c0f595d3d876adc57cab0124bd655"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ae4d4ed80cccf87576ab4833828313f757f9861"
os = "windows"

    [[Enzyme.download]]
    sha256 = "b21a691c8df2cddaf9b02fd4ca6554cd6e3f47961fe343489a78ccf2af682d51"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+4/Enzyme.v0.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
