[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef706cf1260ba4276205128a9e270ba702633058"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "03849fa7c2c3663388f9d6551d989c50662f0751a9554736e8aaff5766f7deff"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acb05df89ba65b721d0c6f4a1a05846cf923e55b"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "19a037065e6f8fb782c0e2af23192d78762ac2ea082b3809fcdab6d5db45a97e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d39d121beecd143ed93d74bf40da1ff27e0f6fed"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "cfacf185eb1bf9d1d4d8d62999f1f65ad435b86fafa0806116a7d72545e2cba7"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0203b672f7ba7f8137f31aa481f9345aca53329a"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "10987cb72dea5e269bfdab9b2ea8b0dba7704d6a0a112a2d79d0f4351bf23b02"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0eb879aa448a470d84cb5476886952463ca6ede8"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1610cc055a0cb8ca3dd980b595638eb40c963728bbe69a78aa820dbcdb5eb60a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3315455970cb71106c9e2f355ca0d2d044c4d56f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "df28240bdccd97b2ea91a52dc07ef3be8bba87a910970a874611102a74d0158e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abd010dfff8789ac4d09d4818c426ca80c4fecb4"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5100a9a9f755fb4dbe79ba2555f02028e6ef2da02901c031bf7c4e5f63643ca5"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01993688ff03c41acd348adf9847cdc0f89c83f4"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "02d737e498696232b8ab7db70788e42bcdf70fc7cbf9fb7b0302bb60eaa4c232"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9bfeeb71fe491ab9a1739bdc2cb13c9c27a0a33"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "2f365ced76504df22eb42b23e2ff84c903fc3aa9e5f6639b083f1dbcc87190e0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05a6425d3da95919e1262d8ac25e348195b21b05"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "cf90569163e52cf47812b4e68444585262fd44773b4bdfe79aec8e1d504d4607"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd428d39462744bc0496018cddd041b1d2509aae"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "11a5188c81ab9157619275dde11292331a9b0bb9333a7fd7d158a27570bc2f6c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e4186c3f81b6c4c2d11eb75cd29085710699272"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "2236362468bffc542e06622ad3d062d27d0feb714901800f9572c7ae5fa9c114"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db24b70b640f353c32b467e788b44bd57e218854"
os = "windows"

    [[Enzyme.download]]
    sha256 = "c07ab018af061ff0926bdc3bb2e8a4c0b1862b9c3496ca74c36d1cd6ed0635d2"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c8cc60301119543a6b2168d6ede176e4ec9d979"
os = "windows"

    [[Enzyme.download]]
    sha256 = "94794b26aa9636dc28e97f1dc1839d2933a064188d6712de27eeb1d038dbdb5a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39444e2a2f00ce5d15711f6f05d53464f46dd0df"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "6e97a39e822577f8ae68fe0e7400fc53e24fb038322eadd93628b9ae4416bb0b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8010de79e702fe103bd1115f69449d4a8454a94b"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "26443b4220405fdc40bf79d7bd93f52c815c235974b183b03a0eec0f1b981bbb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "dadb00585ffb36dc76f11badb3520500357ba5fd"
os = "macos"

    [[Enzyme.download]]
    sha256 = "7efcff2a3d49a9ab1f873a10b7674b1842e78a9bc33caf4ad84784c3f8bf96a6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68a1622fef2eb1f9a619df0e05e59388582748a1"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "656afa9249d4c70042e637effeff6ad08b9413d7a71df49d3dd73ef8a6247fd6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b64afd8d2f1529d54999019ed5f438e87953b456"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "6a9418cc0601046c4fc6290d60767b08205ec6e05946b92c79dcdec1a53ab379"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8d01c33a80d26eba602d6b8cf886ff5856a735f"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "3347a6b573e2ff9b849c5b0707297cc28b70cadb9c384699b2f2239cb072ba09"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3af92d2150648d1f4d41885a68e7fda95b5647e"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "633d99f17a1f18115a82b9c186f126a0f1c1a300941710ce2b92c2f46a97c5b5"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "c29a93a19c71021b358c46236201a57c72599066"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "64012d9c0a436e171f4ae8910004bd45fa1c1da15fb60b39cc638234c653c0d9"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a959167f33edc652779f9a99dc78f8d68943d38b"
os = "windows"

    [[Enzyme.download]]
    sha256 = "184bdf46ba7c21b0443ad3a96b0ddacfbae6e9dc423bf41646c1fe770709ef7a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "360dffa280b3129e113acb5956c3371521f89860"
os = "windows"

    [[Enzyme.download]]
    sha256 = "e1c278c10afc8dc559720ebb89f1cf0323e2017362e62bf8dac5f6220c80f77e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.6+0/Enzyme.v0.0.6.x86_64-w64-mingw32-cxx11.tar.gz"
