[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a864edf145df5fd183b7b72f9db7d315050cfcc"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e05edf7dfa152b94da65f7a7b304a449678d63fadc027dda375b649ecf650b14"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8be2fdacc17cb2c1fd77cfc6cd54ff2f06ffb17c"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ffa231c99e1eb5a568a69af4cdf6151f5e54cf043a9c7832409bccabac2439e7"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8b2a85313dc7890b0ba8bba248c19b70cee4c5f"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "d4bbd433982cd376f665f45d6414bc98ce7a207645677d8152986d446eae2659"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87a138648df23f2e6479edb24dc80d40fbf8c0ab"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "44ed747291c6dd13a389cef3c4541bdb6acf2a4f183db4b2e564baba172d7694"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c8bf598bd6c1b7072675d43d5dc4c992c86133e"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "756e633d1abb206e85ae08f14227ded857efb73bb3073df14eb456fb83ea82ed"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19e5c57d12e54bc624de20932022c06db0de0947"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ff5cbac0e7a1a87003186f83704a0a3859d5de284e5d13d86ef0b999cc9671f0"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff2f06a657f69f7bc011232103474d70ebdc306a"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "056587d513c7e823e351c3599e5d5958bd3966fa68e4df5cf603e8bdba0d0830"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f039f3605e539760cbb23db188b3412bf21caa55"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "214c1963d28c627b17abf541179939712601f309d0486c466d5b684207cd97db"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78c40a65d42446fb70f24db524ed21b8e25b3e0b"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "25b70881c45e509ba3aa8343fcf559d9045cfc83d35f4237be066fe4b2aea821"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59c5f5405abbcddf90f53b42d2ebfefd556512bb"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1470d3aaf5b3e04d8923fdecd6833030cb534de5415abebd823c0075bb740e55"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d86ebe07f5a4601afdf0d751e6c0fa3de94321f"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "10a395ec4fbe8dc34fb18cb28567d8ba964a39f156927025a7c69c69083a1c76"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c602ff8fe8f447f50e647e9cb1786081ae272fa"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "fc4293e84b14de3ad5333e7e3d1454ccec9289ce5dc011161cdc1e6a156c0ae5"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc1c6443b27947f0e8b2ad510e06aee36d37e0a1"
os = "windows"

    [[Enzyme.download]]
    sha256 = "4d08719398cef1a75f5f3676c2967dfa7312977a47820bc00f414a64b0d588be"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7babd171e82a1eeb3f6e0f3c9a0e0847673ac985"
os = "windows"

    [[Enzyme.download]]
    sha256 = "8386c8f9b2c94bb5a670542072136a26c2ac6409e8c230e6057b798c64cbfd3a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e68b27b59ac9419e28cce301a9601998b7e978df"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1665e34393591ca4a56d70a689fd012e5da4ead1de443f1842f24e1f3a804211"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a21248328e9d7de0cd954638b97adffca1d2c349"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "5166a82ff28836e4e6e430fe3eda7f95b74be1e2d798c10ed6eeea5bf918719e"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "503eb4603268875418ba0faeb00419d18f96c2bb"
os = "macos"

    [[Enzyme.download]]
    sha256 = "6cb24f36b3ecdf6113b85cab0367ae4d05c584ade78c72aac3e7a2ff814050e8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e1192886d1de4eb3d5f2921547031658e5841ab"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "630565a0231ea062778e8e17124b34409780dfc495475ca4870e545aba212055"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1d4f80b80049576826180c38b44239933ef680c"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "b4f821efba6a13e5f4abfd5e6b2f4771e2de8cc22ca3eaee2aa8ec8f9dc53857"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67a159fa3dc57d1fd2831eb777473215fa8b5b13"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "38103921c6b7c08cb7e9e058956472105d6535e26c7c8eabbb4abde3decbebca"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1656dcbef1370974d59fb4bacb18bd77b32e2796"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "ef7202a6f88c8afac1937d1cf2d83b8f7bca4ec54f4fa3053c230815194b5e8a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "b875e47a941464333cd4e33603408502d2b2e601"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "0ef6e9d0e226756a7486b6fc0672770a2fb1cebb904ab31c140900464012581a"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b41d78e5fd1a460daa36507bff0ed530381e08df"
os = "windows"

    [[Enzyme.download]]
    sha256 = "ed1e2a39bf045fd73edd7ccd594a4cd282d1c06df5f83d0ab8243a81d76257ee"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb310fc616e25df434288ecb454011b1ea8a69b7"
os = "windows"

    [[Enzyme.download]]
    sha256 = "e93df9017e19c661ffc9f7b6d05e4ec10cf0bd05a1f666a573a8fb6a149dd660"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.1+5/Enzyme.v0.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
