[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7aa75bc8b7cd77e1d14cb0d01f3881b40cd4e25c"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "313197f22c68cbcfc145e5f1590f8b79210f6fe5905cf1951aa438a8b311b3c4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.aarch64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ece421fe85bb27cab8972abbde7d0180945b455b"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "bc6861cf4701851668506e825eb40b035a033a3f527c3390daf2cae24c0d44eb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.aarch64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71db77a0545b1757d948c573d5bb9b201da76c6e"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "484df6d6af8a6119c5fbe8f94a477716fb9710f5c68df589e8e85c64b6a5c543"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.aarch64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f75fbc6ac48ec29ec3b6ac25882931e951eaba49"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "54d7cf34cf8b6058bf63bb99b3fb2b442a30c8fb45eb1be6404a28d8eb50a2b1"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.aarch64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6d5bdb0816cbd55150437d7c3fb39b01367490e"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "26c8850f7107d3960984d5c7ca6410bf0548c89211ce8ecb9d9269d2bbfde52f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cf03341758376f65f24c9958778203095f3471f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "822ddc8ac02292b1c863b9934b8aa6a21607b15f8a94595eb313d56cbf4e0ab8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "545184150f65dd2fb9a82423b1fd579739652ec6"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "40043dd03fe3e550bf6b7d2bb200359c31afd9055132305167525b9cb43beb1f"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Enzyme]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf06a2882e19a815b0fe1ebe9d60c8016e6e14b0"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "a940c8af18dabcf3fa939c0b0be9ffb1fcd8d083723d0d2304df55ee1139cf83"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1c14670f7c87be75a3567da9a82da8e3d574fb0"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "bf990506270509bf23aee789249ba2cde1b4ac4f8405d956e71af704248c1fd4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.i686-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d52aa6bd608a81e247cf2c69ce25e740e54653da"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "6e71350dded5bfefa75fcfe09ae803653e5d337aca7e11f102b36a325e6d0df8"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.i686-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a981b771cfbef4192f66648be70138fc6c80106"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "6ccdf55ca39872885b5ff8e52f482c2abfa214cbbb820bbd6f3322e76cd53586"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.i686-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "077486bd58c0a29261dbd3c9886d4fa5e0ced20a"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "e3e6b3e9207bf8bb85b46e9c8a8ba3e9c4ed65f7ce450f5b573f82463468019c"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.i686-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc75bd93bef2b6a6dd2a930808d6d20382fb9f7d"
os = "windows"

    [[Enzyme.download]]
    sha256 = "be1f0b359d7ff324c2d6a9871360a836b271ad37c25470fa5e6ed4b444d61115"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.i686-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fd7ebb6eb9ca807d0eacd384a40440d04c5313a"
os = "windows"

    [[Enzyme.download]]
    sha256 = "5a6a41824e185e0e2f8aac4de860a3b1cd39ed3d91b91d300f975d0baf01b0e2"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.i686-w64-mingw32-cxx11.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98e6869ef5a516c22e6a7068f766c2eb0fce4301"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "71c79d7cd39459d1d841557aa88a1e0809cc5872447183720b0f110a6209c8d9"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9d3bd15a87b8893e27906ada7678e652bae82e8"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "08287fff3f1152e25b2c81bc1eff8dff61741a89b41a6b555d37dff517691bf6"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "210a585a6803b2c7f50baced48539b76915afbcd"
os = "macos"

    [[Enzyme.download]]
    sha256 = "3290eb59c4beedafa0b5b318f6c085ee8a0bffe7373f38ecafee61c3a3d8ac26"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.x86_64-apple-darwin.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed48d3bf7f33c591e6ac3891fb366bfcb58377d8"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "6dc800f2c6f4b6fdd0eb00b1aaa0201af28ebced15814f99cc7430b96bec7971"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.x86_64-linux-gnu-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec6d12be222ffe0deeca00821b7e68962a39d75f"
libc = "glibc"
os = "linux"

    [[Enzyme.download]]
    sha256 = "1dbdeeebfe5a971fa432f4abb0d3f1921cb60b1fb9bdc8eeedf25e37b9fca83b"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.x86_64-linux-gnu-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "126ee4fdfd923d5138f166e0786dce0a7b611923"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "b34514606726a0e16595cd43e251dfd63ecb167c4c6fd69613b451693fc016bb"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.x86_64-linux-musl-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "942e35cd35901c8609aab7515ba95c859c552ba1"
libc = "musl"
os = "linux"

    [[Enzyme.download]]
    sha256 = "358e6982f4dc14064ffeb2c7bd3624cffcdf9aa98445caf399915d3960f6afa4"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.x86_64-linux-musl-cxx11.tar.gz"
[[Enzyme]]
arch = "x86_64"
git-tree-sha1 = "08696f45c5be3bba7472b592f1d9886c2b01ae5e"
os = "freebsd"

    [[Enzyme.download]]
    sha256 = "69ab2fd40fea399b9eb1c51b9d4917597c4a990e9c3c12ca3cd2ef6a3590b54d"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.x86_64-unknown-freebsd.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69f3f48c9ba2f8a4a3a584fc9b5121a5924a48fd"
os = "windows"

    [[Enzyme.download]]
    sha256 = "2bc04bfdbef41783af59c0947a647480f4978bc3bd39ef574dd849d5a1251cf7"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.x86_64-w64-mingw32-cxx03.tar.gz"
[[Enzyme]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e1fae4eabb3a7e9874d62fb3602a73e4a4293a4"
os = "windows"

    [[Enzyme.download]]
    sha256 = "157d69a91bce27482b223f7f2b0b9fe188cda00d89bf81172cf03c0138d76e94"
    url = "https://github.com/JuliaBinaryWrappers/Enzyme_jll.jl/releases/download/Enzyme-v0.0.12+0/Enzyme.v0.0.12.x86_64-w64-mingw32-cxx11.tar.gz"
